/**
 * Created by Denis on 13.03.2017.
 */
/* const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS'; */
export const RENDER_TILE_LAYERS = 'RENDER_TILE_LAYERS';
export const GET_LOCATION = 'GET_LOCATION';
